version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies for React and Lambda...
      - cd frontend && npm install
      - cd ../backend && npm install
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      - unzip terraform_1.5.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo Building React app...
      - cd ../frontend && npm run build
      - echo Zipping Lambda function...
      - cd ../backend && zip -r lambda.zip .
  post_build:
    commands:
      - echo Syncing React build files to S3...
      - aws s3 sync ../frontend/build/ s3://file-upload-project-bucket/ --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E3ATBMXKMH02CC --paths "/*"
      - echo Uploading Lambda zip to S3...
      - aws s3 cp lambda.zip s3://file-upload-project-bucket/
      - echo Updating Lambda function code...
      - aws lambda update-function-code --function-name file-upload-backend --s3-bucket file-upload-project-bucket --s3-key lambda.zip
      - echo Copying Lambda zip to Terraform directory...
      - cp ../backend/lambda.zip ../terraform/
      - echo Initializing Terraform...
      - cd ../terraform
      - terraform init
      - echo Applying Terraform configuration...
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build